/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '.theme-dark'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          foreground: 'var(--color-primary-foreground)',
          subtle: 'var(--color-primary-subtle)',
          'subtle-text': 'var(--color-primary-subtle-text)',
          border: 'var(--color-primary-border)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          foreground: 'var(--color-secondary-foreground)',
          subtle: 'var(--color-secondary-subtle)',
        },
        background: {
          DEFAULT: 'var(--color-background)',
          surface: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          subtle: 'var(--color-surface-subtle)',
          hover: 'var(--color-surface-hover)',
          muted: 'var(--color-surface-muted)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          subtle: 'var(--color-surface-subtle)',
          hover: 'var(--color-surface-hover)',
          muted: 'var(--color-surface-muted)',
        },
        foreground: {
          DEFAULT: 'var(--color-foreground)',
          secondary: 'var(--color-foreground-secondary)',
          muted: 'var(--color-foreground-muted)',
          subtle: 'var(--color-foreground-subtle)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          subtle: 'var(--color-border-subtle)',
          strong: 'var(--color-border-strong)',
          primary: 'var(--color-primary-border)',
        },
        card: {
          DEFAULT: 'var(--color-card)',
          hover: 'var(--color-card-hover)',
          active: 'var(--color-card-active)',
          subtle: 'var(--color-card-subtle)',
          elevated: 'var(--color-card-elevated)',
          border: 'var(--color-card-border)',
          'border-subtle': 'var(--color-card-border-subtle)',
          'border-hover': 'var(--color-card-border-hover)',
        },
        container: {
          sunken: 'var(--color-container-sunken)',
          'sunken-border': 'var(--color-container-sunken-border)',
          interactive: 'var(--color-container-interactive)',
          'interactive-hover': 'var(--color-container-interactive-hover)',
          accent: 'var(--color-container-accent)',
          'accent-border': 'var(--color-container-accent-border)',
        },
        eco: {
          core: 'var(--eco-icon-core)',
          'core-bg': 'var(--eco-icon-core-bg)',
          'core-border': 'var(--eco-icon-core-border)',
          ops: 'var(--eco-icon-ops)',
          'ops-bg': 'var(--eco-icon-ops-bg)',
          'ops-border': 'var(--eco-icon-ops-border)',
          intel: 'var(--eco-icon-intel)',
          'intel-bg': 'var(--eco-icon-intel-bg)',
          'intel-border': 'var(--eco-icon-intel-border)',
          exp: 'var(--eco-icon-exp)',
          'exp-bg': 'var(--eco-icon-exp-bg)',
          'exp-border': 'var(--eco-icon-exp-border)',
        },
        input: {
          DEFAULT: 'var(--color-input)',
          border: 'var(--color-input-border)',
          focus: 'var(--color-input-focus)',
          text: 'var(--color-input-text)',
          placeholder: 'var(--color-input-placeholder)',
        },
      },
    },
  },
};
