/**
 * Legal page content (Step 15). Written for what the Artify platform actually stores (see Artify-Backend docs/OPERATIONS.md §6 retention table and
 * docs/META_APP_REVIEW.md). Nothing here is copied from another company and it makes no certification or uptime claims.
 *
 * Values the OWNER must confirm are marked with `{{OWNER: …}}`. The page renders them as a visible highlighted placeholder, and `tests/legal.test.tsx`
 * lists them so none is forgotten. Replace each marker with the real value (or delete the sentence) before submitting the app to Meta.
 * This text is a good-faith description of the platform, not legal advice: have it reviewed by a lawyer for the jurisdictions you operate in.
 */
export type LegalType = 'privacy' | 'terms' | 'data-deletion';

export interface LegalSection { heading: string; paragraphs?: string[]; bullets?: string[]; table?: { head: string[]; rows: string[][] } }
export interface LegalDoc { title: string; seoDescription: string; path: string; effective: string; intro: string[]; sections: LegalSection[] }

export const OWNER_MARKER = /\{\{OWNER:\s*([^}]+)\}\}/g;

export const LEGAL_LAST_UPDATED = '9 October 2026';

const PRIVACY: LegalDoc = {
  title: 'Privacy Policy',
  seoDescription: 'How Artify Solutions collects, uses, stores and deletes personal data on its website and in its Control Center, including data received from Facebook and Instagram.',
  path: '/privacy',
  effective: LEGAL_LAST_UPDATED,
  intro: [
    'This policy explains what personal data Artify Solutions ("we") collects through artifysols.com and through our Control Center software, why, how long we keep it, who else handles it, and how you can ask us to delete it.',
    'Artify Solutions is a trading name and is not yet registered as a company. We will publish our registered legal name and address here once registration is complete. Until then, contact us for any privacy question or request at ArtifySols@gmail.com.',
  ],
  sections: [
    {
      heading: '1. Who this covers',
      bullets: [
        'People who visit artifysols.com or one of our landing pages.',
        'People who send us a message or fill in a form (enquiries, briefs, partner access requests).',
        'Customers and their staff who use the Control Center.',
        'People who write to, comment on, mention or message a Facebook Page or Instagram professional account that one of our customers (or we) manage through the Control Center.',
      ],
    },
    {
      heading: '2. What we collect',
      table: {
        head: ['Data', 'Where it comes from', 'What we do with it'],
        rows: [
          ['Page views: page path, referrer, campaign (UTM) tags and a random identifier that lives only in your browser tab', 'Our website', 'Count visits and measure which pages and campaigns work. No names or email addresses are stored with these events.'],
          ['Form and landing page submissions: the answers you type (for example name, email, phone, company, message), the page you were on, your IP address and browser details, whether you ticked the consent box', 'You', 'Reply to you, create a lead in our CRM, keep proof of consent, protect forms from abuse.'],
          ['Customer account data: name, work email, role, login history, security settings', 'You or your administrator', 'Run your account and keep it secure. Passwords are stored only as one-way hashes.'],
          ['Facebook/Instagram messages, comments, mentions and visitor posts sent to a connected Page or professional account: the text, the sender\'s public name or handle and Meta\'s identifier for them, time stamps', 'Meta, through the permissions the connecting customer grants', 'Show them in the shared inbox, let the customer reply, and measure response times.'],
          ['Facebook/Instagram account and Page information and performance numbers (followers, reach, engagement, post metrics)', 'Meta, with the connecting person\'s permission', 'Show analytics to the customer who connected the account.'],
          ['Access tokens that let the Control Center act on a connected Page or Instagram account', 'Meta, when a person connects an account', 'Publish, read and reply on that account. Stored encrypted; never shown in the interface or logs. Deleted when the account is disconnected or Meta tells us access was removed.'],
          ['Audit records: who did what and when inside the Control Center', 'Generated by the system', 'Security and accountability. They contain identifiers and counts, not message text.'],
        ],
      },
      paragraphs: ['We do not sell personal data. We do not use data received from Meta to build advertising profiles, and we do not share it with data brokers.'],
    },
    {
      heading: '3. Why we use it (purposes)',
      bullets: [
        'To provide and secure the Control Center and the website.',
        'To answer enquiries and manage customer relationships.',
        'To let a customer manage their own Facebook Page and Instagram account: publish posts, read and answer messages and comments, and see analytics.',
        'To measure how the website performs.',
        'To meet legal obligations and to keep records of consent and of how privacy requests were handled.',
      ],
      paragraphs: ['Where the law requires a legal basis, we rely on: performing a contract with our customers; our legitimate interest in running and securing the service and measuring the website; your consent where we ask for it (for example the tick box on a form); and legal obligation. We aim to handle personal data in line with the principles of the UAE Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data (PDPL) and, for people in the European Economic Area and the United Kingdom, the principles of the GDPR: lawfulness, fairness and transparency, purpose limitation, data minimisation, accuracy, storage limitation, security and accountability.'],
    },
    {
      heading: '4. Automated processing (AI)',
      paragraphs: [
        'The Control Center can use an AI model to classify incoming messages (topic, sentiment, priority) and to draft replies for a person to review. When AI features are enabled, the text of a message is sent to Google (Gemini) to be analysed; we do not send passwords or access tokens. Draft replies are not sent automatically unless a workspace has explicitly switched automatic replies on, which is off by default. We do not use messages received through Meta to train AI models.',
      ],
    },
    {
      heading: '5. Who else handles the data',
      bullets: [
        'Hosting and delivery of the website and API: Vercel.',
        'Database: Supabase (PostgreSQL).',
        'Facebook and Instagram: Meta Platforms. When a customer connects an account, Meta\'s own privacy policy applies to the data on Meta\'s side.',
        'AI processing, if enabled: the provider named in section 4.',
        'Email: the platform does not currently send email by itself. When we reply to you by email we use our own mailbox, hosted by Google (Gmail).',
        'Professional advisers, authorities and courts, where we are legally required to disclose.',
      ],
      paragraphs: ['Our database is hosted in Tokyo, Japan (Supabase, region ap-northeast-1). The Control Center API runs on Vercel in Tokyo, and the public website is served from Vercel\'s United States East region. This means personal data can be processed outside the country where you live. Where the law requires safeguards for such transfers, we use providers that publish their own data protection terms, together with the other protections in this policy. Contact us if you want details.'],
    },
    {
      heading: '6. How long we keep it',
      table: {
        head: ['Data', 'Kept for'],
        rows: [
          ['Social inbox conversations and messages', '180 days by default (each workspace can set 7 to 3650 days), then deleted automatically'],
          ['Website analytics events', '395 days (13 months), then deleted automatically'],
          ['Login sessions after they end', '30 days'],
          ['Encrypted backup exports', '30 days (the newest three are always kept)'],
          ['Leads, contacts, clients and form submissions', 'While the enquiry or relationship is active; reviewed at least yearly; erased on a verified request'],
          ['Consent register (source, status, time; no personal data)', 'Kept as proof of consent'],
          ['Audit log and privacy-request records (identifiers and counts only)', 'Kept for security and accountability'],
          ['Facebook/Instagram access tokens', 'Until the account is disconnected, access is removed on Meta\'s side, or you ask us to delete your data'],
        ],
      },
      paragraphs: ['These are the periods currently configured in the platform. We review them at least once a year, and if we change them we will update this page.'],
    },
    {
      heading: '7. Your rights and how to use them',
      paragraphs: [
        'Depending on where you live you may have the right to ask for a copy of your data, to correct it, to have it deleted, to restrict or object to its use, and to withdraw consent. To use any of these, email ArtifySols@gmail.com from the address we hold for you, or use the steps on our Data Deletion page (/data-deletion). We may need to confirm it is you. We aim to answer within 30 days.',
        'You can also complain to the data protection authority where you live, for example the UAE Data Office in the United Arab Emirates, or your national supervisory authority in the EU or UK.',
      ],
    },
    {
      heading: '8. Deleting data that came from Facebook or Instagram',
      paragraphs: [
        'If you used Facebook or Instagram to sign in to a service of ours, or you want data that came from Meta removed, see /data-deletion. You can remove our app (shown on Facebook as "Artify Social Media Management") from your Facebook settings at any time; Facebook then tells us, and we disconnect the account and delete the stored access tokens. You can also ask Facebook to send us a data deletion request: we confirm it with a code and a status page, a team member reviews it, and then we delete or anonymise the data we hold that is linked to your Facebook account.',
      ],
    },
    {
      heading: '9. Security',
      paragraphs: [
        'Access to the Control Center is controlled by roles and permissions; sensitive actions such as erasing personal data need a second person to approve; access tokens are stored encrypted; data is encrypted in transit; every privacy action is recorded in an audit log. No system is perfectly secure; if a breach affects you we will notify you and the authorities as the law requires.',
      ],
    },
    {
      heading: '10. Children',
      paragraphs: ['Our services are for businesses and are not directed at children. We do not knowingly collect personal data from anyone under 18; if you believe a child has sent us personal data, write to us and we will delete it.'],
    },
    {
      heading: '11. Changes',
      paragraphs: ['If we make a material change we will update the date at the top of this page and, where the change affects how we use data you gave us, tell you directly.'],
    },
  ],
};

const TERMS: LegalDoc = {
  title: 'Terms of Service',
  seoDescription: 'The terms that apply when you use the Artify Solutions website and the Artify Control Center.',
  path: '/terms',
  effective: LEGAL_LAST_UPDATED,
  intro: [
    'These terms apply to the artifysols.com website and to the Control Center software provided by Artify Solutions ("we"), a trading name that is not yet registered as a company. We will publish our registered legal name and address here once registration is complete. Contact: ArtifySols@gmail.com.',
    'Customer contracts, statements of work or order forms that we sign with you take precedence over these terms where they differ.',
  ],
  sections: [
    { heading: '1. The service', paragraphs: ['The Control Center lets a business manage its website content, customer enquiries, marketing pages and social media accounts (publishing, inbox, analytics). Features depend on the plan or project agreed with us and on the permissions Meta and other platforms grant.'] },
    { heading: '2. Accounts', bullets: ['You must give accurate information and keep your login details secret. You are responsible for what happens under your account.', 'Administrators decide who in their organization gets which role. Tell us promptly if you think an account was compromised.'] },
    { heading: '3. Connected third-party accounts', paragraphs: ['If you connect a Facebook Page or Instagram professional account, you confirm you are allowed to manage it. You remain bound by Meta\'s terms and policies, and by the rules of any other platform you connect. We act on those accounts only as you instruct through the Control Center, and you can disconnect an account at any time. We are not responsible for a platform changing, limiting or withdrawing access.'] },
    { heading: '4. Acceptable use', bullets: ['No unlawful, deceptive, harassing or infringing content, and no spam.', 'No attempts to disrupt, probe or bypass the security of the service, or to access another customer\'s data.', 'Use automation features (for example automatic replies) responsibly and in line with the rules of the platforms involved.'] },
    { heading: '5. Your content and data', paragraphs: ['You keep ownership of the content and data you put into the service. You give us the right to host, process and display it as needed to provide the service to you. How we handle personal data is described in the Privacy Policy.'] },
    { heading: '6. Our intellectual property', paragraphs: ['We and our licensors own the software, design and documentation. Work created specifically for you under a separate agreement belongs to you once it has been paid for in full, unless that agreement says otherwise. Our pre-existing tools, templates and know-how remain ours, and open-source components stay under their own licences.'] },
    { heading: '7. Availability and changes', paragraphs: ['We work to keep the service available, but we do not promise uninterrupted operation unless a signed agreement says so. We may change or retire features; where a change materially affects you we will give reasonable notice. We give no uptime guarantee unless a signed agreement states one.'] },
    { heading: '8. Fees', paragraphs: ['Fees and payment terms are set in each written proposal, order form or statement of work. Where none applies, we do not charge for using the website.'] },
    { heading: '9. Suspension and ending', paragraphs: ['You may stop using the service at any time. We may suspend or end access for breach of these terms or to protect the service or others. On ending, you can ask for an export of your data and for deletion as described in the Privacy Policy.'] },
    { heading: '10. Liability', paragraphs: ['To the extent the law allows: the service is provided "as is", and we give no warranty that it will be uninterrupted or error-free; we are not liable for indirect or consequential loss, or for loss of profit, revenue, data or goodwill; and our total liability for any claim relating to the service is limited to the fees you paid us for the service in the 12 months before the claim arose. Nothing in these terms limits liability that cannot be limited by law, including liability for fraud or intentional misconduct.'] },
    { heading: '11. Governing law', paragraphs: ['These terms are governed by the laws of the United Arab Emirates, including the federal laws applicable in the emirate where we are established. Disputes are brought before the competent courts there, unless a separate signed agreement says otherwise.'] },
    { heading: '12. Changes to these terms', paragraphs: ['We may update these terms; the date at the top shows the current version. Continuing to use the service after a change means you accept it.'] },
  ],
};

const DELETION: LegalDoc = {
  title: 'Data Deletion Instructions',
  seoDescription: 'How to ask Artify Solutions to delete your personal data, including data connected to your Facebook or Instagram account.',
  path: '/data-deletion',
  effective: LEGAL_LAST_UPDATED,
  intro: [
    'You can ask us to delete the personal data we hold about you. This page explains the three ways to do it and what happens next. For what we collect and how long we keep it, see the Privacy Policy.',
  ],
  sections: [
    {
      heading: 'Option 1: remove our app from your Facebook account',
      paragraphs: ['This is for people whose Facebook or Instagram account is connected to a Page we manage through the Control Center, and for anyone who wants Facebook to tell us to delete their data.'],
      bullets: [
        'Open Facebook and go to Settings & privacy, then Settings.',
        'Open "Apps and websites" (it may be called "Business integrations" or "Active apps").',
        'Find "Artify Social Media Management" (the app we run under the name Artify Solutions) and choose Remove.',
        'Tick the option to delete the posts, photos and videos the app published, if you want that, and confirm.',
      ],
    },
    {
      heading: 'Option 2: ask Facebook to send us a data deletion request',
      paragraphs: [
        'When you remove the app (Option 1), Facebook sends us a signed data deletion request. We immediately disconnect any account you connected and delete its stored access tokens. We then create a deletion request for a team member to review. Nothing else is deleted until a person has reviewed and approved it, which protects you from a mistaken or forged request.',
        'Facebook shows you a confirmation code that starts with "MDR-". Enter it on our status page (/data-deletion-status) at any time to see the state of your request: in review, completed, declined, or nothing held. The page shows no personal data.',
        'What deletion removes: the Facebook/Instagram access tokens, the connection between your Facebook account and the accounts you connected, and, for people who commented on or mentioned a Page we manage, the stored message text and your name and handle on those conversations. Records that contain no personal data, such as the consent register and the audit log of privacy actions, are kept as proof that the request was handled.',
      ],
    },
    {
      heading: 'Option 3: write to us',
      paragraphs: [
        'Email ArtifySols@gmail.com with the subject "Data deletion request". From the address you used with us, tell us who you are and which service or Page this concerns. If your request is about a Facebook or Instagram message you sent to a Page, include the name of the Page and roughly when you wrote, because Meta does not tell us who sent a direct message when it forwards a deletion request. We may ask you to confirm your identity. We aim to reply within 30 days.',
      ],
    },
    {
      heading: 'What we cannot delete',
      paragraphs: ['We keep what the law requires us to keep, and records that contain no personal data and prove how requests were handled. Data a customer holds in their own systems, and data held by Meta, is outside our control; Meta handles requests about its own copy.'],
    },
  ],
};

export const LEGAL_DOCS: Record<LegalType, LegalDoc> = { privacy: PRIVACY, terms: TERMS, 'data-deletion': DELETION };

/** Every owner marker still present in the published text, for the pre-submission checklist and the test. */
export function listOwnerMarkers(): string[] {
  const text = JSON.stringify(LEGAL_DOCS);
  return [...new Set([...text.matchAll(OWNER_MARKER)].map((m) => m[1]!.trim()))];
}
